Разметка внутренних страниц
htmlacademy-adaptive/1712611-cat-energy-24 pull request #3
Opened 2021-11-30 17:38 UTC by Irina-Melnik

2021-11-30 20:51 UTC, summertime-fms requested changes

2021-11-30 20:51 UTC, summertime-fms commented on source/catalog.html
> +    <section class="additional-goods">
Давай покороче. additional просто

2021-11-30 20:51 UTC, summertime-fms commented on source/catalog.html
> +    <section class="special-promo">
просто promo

2021-11-30 20:51 UTC, summertime-fms commented on source/catalog.html
> +            width="320" height="362" allowfullscreen="" loading="lazy" title="Офис компании по адресу ул. Большая
allowfullscreen нам не нужен)

2021-11-30 20:51 UTC, summertime-fms commented on source/catalog.html
> +      <a class="footer__logo footer-logo" href="#">
Ведет на главную уже. В форме тоже поправить

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +        <form class="program-choice__form form" action="https://echo.htmlacademy.ru/courses" method="get">
POST тут будет вместо get. Мы же не запрашиваем данные как например в поисковой строке. Мы наоборот отправляем

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +              <input class="personal-data__input personal-data__input--weight input" type="number" id="weight"
А что ты тут собралась модифицировать?)

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +              <label class="personal-data__label label" for="weight">Вес&nbsp;(кг):*</label>
для звездочек этих есть тег `sup`

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +              <input class="personal-data__input personal-data__input--age input" type="number" id="age" name="age"
Ну и max давай добавим в рамках разумного. Сколько максимум живут коты?..

-

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +                <input class="visually-hidden" type="radio" name="program" value="weight-loss-program"
короче лучше. просто loss. в следующей просто gain

2021-11-30 20:51 UTC, summertime-fms commented on source/form.html
> +                <label class="filter-checkbox__label checkbox" for="optional-sweetener">сахарозаменитель</label>
Есть критерий на единообразие и тут могут придраться. Везде в разметке пишешь с большой буквы а тут с маленькой. Регистр меняется стилями)

2021-12-01 06:39 UTC, Irina-Melnik commented on source/catalog.html
> +    <section class="special-promo">
promo уже есть нв главной странице, сделаю тогда просто offer

2021-12-01 06:55 UTC, Irina-Melnik commented on source/form.html
> +              <input class="personal-data__input personal-data__input--weight input" type="number" id="weight"
Действительно, тут ничего не буду модифицировать. А вот где e-mail и телефон там будут свои иконки у каждого input, правильно?

2021-12-01 07:35 UTC, merged